import { useEffect, useState } from "react";
import { useAuth } from "@/context/AuthContext";
import { useToast } from "@/components/Toast";
import { ATTRIBUTES, supabase, xpProgress } from "@/lib/supabase";
import { Award, CalendarDays, Check, Coins, Crown, Flame, LockKeyhole, Mail, Save, Shield, Sparkles, UserRound, Zap } from "lucide-react";

export function ProfilePage(){ const {profile,session,updatePassword,refreshProfile}=useAuth(); const {toast}=useToast(); const [name,setName]=useState(""); const [password,setPassword]=useState(""); const [saving,setSaving]=useState(false); const [statsLoading,setStatsLoading]=useState(false); const [completed,setCompleted]=useState(0);
  useEffect(()=>{setName(profile?.username??"")},[profile?.username]);
  useEffect(()=>{if(!profile)return; (async()=>{setStatsLoading(true); const {count}=await supabase.from("task_completions").select("id",{count:"exact",head:true}); setCompleted(count??0); setStatsLoading(false)})()},[profile]);
  if(!profile) return <div className="panel p-10 text-center"><Shield className="mx-auto h-10 w-10 text-violet-300" /><h1 className="mt-4 text-xl font-black">Character sheet unavailable</h1><p className="mt-2 text-sm text-slate-500">Your profile row could not be loaded.</p></div>;
  const progress=xpProgress(profile.xp); const joined=new Date(profile.created_at); const letter=(profile.username||"H").slice(0,1).toUpperCase(); const nextLevelXp=profile.xp+Math.max(0,progress.needed-progress.current); const saveName=async()=>{const clean=name.trim();if(!clean||clean.length>30)return toast("Name must be 1–30 characters","error");setSaving(true);const {error}=await supabase.rpc("update_username",{new_name:clean});if(error)toast(error.message,"error");else{await refreshProfile();toast("Character name updated","success")}setSaving(false)}; const savePassword=async()=>{if(password.length<6)return toast("Use at least 6 characters","error");const {error}=await updatePassword(password);if(error)toast(error,"error");else{setPassword("");toast("Password updated","success")}};
  return <div className="space-y-6 animate-enter"><div><div className="eyebrow text-violet-300">Character sheet</div><div className="mt-1 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-black tracking-tight text-white sm:text-4xl">Profile & progression</h1><p className="mt-1 text-sm text-slate-500">Tune the identity behind your real-life character.</p></div><div className="flex items-center gap-2 text-xs text-slate-500"><CalendarDays className="h-4 w-4"/>Joined {joined.toLocaleDateString()}</div></div></div>
    <section className="panel relative overflow-hidden p-6 sm:p-8"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-violet-500/10 blur-3xl"/><div className="relative grid gap-6 lg:grid-cols-[auto_1fr] lg:items-center"><div className="grid h-28 w-28 place-items-center rounded-[2rem] bg-gradient-to-br from-sky-500 to-violet-600 text-5xl font-black shadow-2xl shadow-violet-500/10">{letter}</div><div><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="flex-1"><label className="eyebrow">Display name</label><input value={name} onChange={e=>setName(e.target.value)} className="field mt-2 text-xl font-black" maxLength={30}/></div><button onClick={saveName} disabled={saving||name===profile.username} className="btn-primary sm:self-end">{saving?<span className="animate-pulse">Saving…</span>:<><Save className="h-4 w-4"/> Save name</>}</button></div><div className="mt-4 flex flex-wrap gap-3 text-sm text-slate-400"><span className="inline-flex items-center gap-2 rounded-full bg-white/[0.04] px-3 py-1.5"><Crown className="h-4 w-4 text-amber-300"/>Level {profile.level}</span><span className="inline-flex items-center gap-2 rounded-full bg-white/[0.04] px-3 py-1.5"><Zap className="h-4 w-4 text-sky-300"/>{profile.xp.toLocaleString()} XP</span><span className="inline-flex items-center gap-2 rounded-full bg-white/[0.04] px-3 py-1.5"><Coins className="h-4 w-4 text-amber-300"/>{profile.gold.toLocaleString()} Gold</span></div><div className="mt-6"><div className="mb-2 flex justify-between text-xs text-slate-500"><span>Level {profile.level} → {profile.level+1}</span><span>{Math.round(progress.percent)}%</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-sky-400 via-violet-400 to-fuchsia-400 transition-all" style={{width:`${progress.percent}%`}}/></div><div className="mt-2 text-xs text-slate-600">{progress.current.toLocaleString()} / {progress.needed.toLocaleString()} XP in this level · next threshold at {nextLevelXp.toLocaleString()} XP</div></div></div></div></section>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{ATTRIBUTES.map(a=><div key={a.value} className="panel p-5"><div className="text-xs font-bold uppercase tracking-wider text-slate-600">{a.label}</div><div className="mt-2 text-3xl font-black text-white">{profile[a.value]}</div><div className="mt-3 h-1.5 rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-sky-400 to-violet-500" style={{width:`${Math.min(100,profile[a.value]*4)}%`}}/></div></div>)}</section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="panel p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-amber-500/10 text-amber-300"><Award/></div><div><h2 className="font-black text-white">Journey stats</h2><p className="text-xs text-slate-600">Your long-game momentum</p></div></div><div className="mt-5 grid grid-cols-2 gap-3"><Mini label="Completed quests" value={statsLoading?"…":String(completed)} icon={Check}/><Mini label="Best streak" value={`${profile.best_streak} days`} icon={Flame}/><Mini label="Current streak" value={`${profile.current_streak} days`} icon={Flame}/><Mini label="Total gold" value={profile.gold.toLocaleString()} icon={Coins}/></div></div>
      <div className="panel p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-sky-500/10 text-sky-300"><LockKeyhole/></div><div><h2 className="font-black text-white">Account security</h2><p className="text-xs text-slate-600">Keep your character account protected</p></div></div><div className="mt-5 flex items-center gap-3 rounded-2xl bg-white/[0.025] p-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-500/10 text-emerald-300"><Mail/></div><div className="min-w-0"><div className="text-xs text-slate-500">Account email</div><div className="truncate text-sm font-semibold text-white">{session?.user.email ?? "Signed-in account"}</div></div></div><div className="mt-4 flex gap-2"><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="New password" className="field"/><button onClick={savePassword} className="btn-secondary shrink-0"><Save className="h-4 w-4"/> Update</button></div></div></section>
  </div> }
function Mini({label,value,icon:Icon}:{label:string;value:string;icon:typeof Check}){return <div className="rounded-2xl bg-white/[0.025] p-4"><div className="flex items-center gap-2 text-xs text-slate-600"><Icon className="h-3.5 w-3.5"/>{label}</div><div className="mt-2 text-lg font-black text-white">{value}</div></div>}
