import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/context/AuthContext";
import { ATTRIBUTES, CATEGORIES, DIFFICULTIES, supabase, type Quest, type QuestAttribute, type QuestCategory, type QuestDifficulty } from "@/lib/supabase";
import { useToast } from "@/components/Toast";
import { CalendarDays, Check, CheckCircle2, Clock3, Code2, Dumbbell, Filter, Heart, ListFilter, Pencil, Plus, Search, Sparkles, Trash2, X, Zap } from "lucide-react";

type Tab="active"|"completed"|"all";
const CAT_ICONS={study:Sparkles,coding:Code2,exercise:Dumbbell,reading:Sparkles,personal:Heart,other:Sparkles};
const DIFF_CLASS={easy:"bg-emerald-400/10 text-emerald-300",medium:"bg-amber-400/10 text-amber-300",hard:"bg-orange-400/10 text-orange-300",epic:"bg-rose-400/10 text-rose-300"};

export function Quests(){const {refreshProfile}=useAuth();const {toast}=useToast();const[quests,setQuests]=useState<Quest[]>([]);const[loading,setLoading]=useState(true);const[tab,setTab]=useState<Tab>("active");const[search,setSearch]=useState("");const[modal,setModal]=useState(false);const[editing,setEditing]=useState<Quest|null>(null);const[busy,setBusy]=useState<string|null>(null);
 const load=async()=>{setLoading(true);let q=supabase.from("quests").select("*").order("created_at",{ascending:false});if(tab==="active")q=q.eq("completed",false);else if(tab==="completed")q=q.eq("completed",true);const {data,error}=await q;if(error)toast(error.message,"error");setQuests((data??[]) as Quest[]);setLoading(false)};useEffect(()=>{void load()},[tab]);
 const visible=useMemo(()=>quests.filter(q=>`${q.title} ${q.description} ${q.category}`.toLowerCase().includes(search.toLowerCase())),[quests,search]);
 const complete=async(q:Quest)=>{if(busy)return;setBusy(q.id);const{data,error}=await supabase.rpc("complete_quest",{quest_uuid:q.id});if(error)toast(error.message,"error");else{toast(`Quest complete · +${data.xp_awarded} XP · +${data.gold_awarded} Gold`,`success`);await refreshProfile();await load()}setBusy(null)};
 const remove=async(q:Quest)=>{const old=quests;setQuests(v=>v.filter(x=>x.id!==q.id));const{error}=await supabase.from("quests").delete().eq("id",q.id);if(error){setQuests(old);toast(error.message,"error")}else toast("Quest deleted","info")};
 return <div className="space-y-6 animate-enter"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="eyebrow text-sky-300">Quest board</div><h1 className="mt-1 text-3xl font-black text-white sm:text-4xl">Make progress visible.</h1><p className="mt-2 text-sm text-slate-500">Turn intentions into concrete actions, then cash them in for momentum.</p></div><button className="btn-primary" onClick={()=>{setEditing(null);setModal(true)}}><Plus className="h-4 w-4"/> New quest</button></div>
 <div className="panel flex flex-col gap-3 p-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-1 rounded-2xl bg-black/20 p-1">{([['active','Active'],['completed','Completed'],['all','All']] as [Tab,string][]).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${tab===id?'bg-white/[0.08] text-white':'text-slate-500 hover:text-slate-200'}`}>{label}</button>)}</div><div className="relative w-full sm:max-w-xs"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search quests…" className="field !pl-9 !py-2.5"/></div></div>
 {loading?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3,4,5,6].map(i=><div key={i} className="panel h-52 animate-pulse bg-white/[0.02]"/>)}</div>:visible.length===0?<div className="panel p-12 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-sky-500/10 text-sky-300"><ListFilter/></div><h2 className="mt-4 text-xl font-black text-white">Nothing on this filter</h2><p className="mt-2 text-sm text-slate-500">Create a quest or change the filter to see more of your adventure.</p><button onClick={()=>{setEditing(null);setModal(true)}} className="btn-primary mt-5"><Plus className="h-4 w-4"/> Create quest</button></div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map(q=><QuestCard key={q.id} quest={q} onComplete={complete} onEdit={q=>{setEditing(q);setModal(true)}} onDelete={remove} busy={busy===q.id}/>)}</div>}
 {modal&&<QuestModal quest={editing} onClose={()=>setModal(false)} onSaved={()=>{setModal(false);void load()}}/>}</div>}

function QuestCard({quest,onComplete,onEdit,onDelete,busy}:{quest:Quest;onComplete:(q:Quest)=>void;onEdit:(q:Quest)=>void;onDelete:(q:Quest)=>void;busy:boolean}){const Icon=CAT_ICONS[quest.category]??Sparkles;const overdue=!!quest.due_date&&!quest.completed&&new Date(quest.due_date)<new Date(new Date().toDateString());return <article className={`panel group relative overflow-hidden p-5 transition hover:-translate-y-0.5 hover:border-white/[0.12] ${quest.completed?'opacity-70':''}`}><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-sky-400/10 text-sky-300"><Icon className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h2 className={`font-black text-white ${quest.completed?'line-through':''}`}>{quest.title}</h2><div className="flex gap-1 opacity-0 transition group-hover:opacity-100"><button onClick={()=>onEdit(quest)} className="rounded-xl p-2 text-slate-500 hover:bg-white/[0.05] hover:text-sky-300"><Pencil className="h-4 w-4"/></button>{!quest.completed&&<button onClick={()=>onDelete(quest)} className="rounded-xl p-2 text-slate-500 hover:bg-rose-500/10 hover:text-rose-300"><Trash2 className="h-4 w-4"/></button>}</div></div><div className="mt-1 text-xs capitalize text-slate-600">{quest.category} · {quest.attribute}</div></div></div>{quest.description&&<p className="mt-4 line-clamp-2 text-sm leading-6 text-slate-500">{quest.description}</p>}<div className="mt-4 flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${DIFF_CLASS[quest.difficulty]}`}>{quest.difficulty}</span><span className="inline-flex items-center gap-1 rounded-full bg-sky-400/10 px-2.5 py-1 text-[11px] font-bold text-sky-300"><Zap className="h-3 w-3"/>+{quest.xp_reward} XP</span><span className="rounded-full bg-white/[0.04] px-2.5 py-1 text-[11px] text-slate-500">+{quest.gold_reward} gold</span></div><div className="mt-5 flex items-center justify-between gap-3"><span className={`inline-flex items-center gap-1.5 text-xs ${overdue?'text-rose-300':'text-slate-600'}`}><CalendarDays className="h-3.5 w-3.5"/>{quest.due_date?new Date(quest.due_date).toLocaleDateString():"No deadline"}{overdue?' · Overdue':''}</span>{quest.completed?<span className="inline-flex items-center gap-1.5 text-xs font-bold text-emerald-300"><CheckCircle2 className="h-4 w-4"/>Completed</span>:<button disabled={busy} onClick={()=>onComplete(quest)} className="btn-primary !rounded-xl !px-3 !py-2">{busy?"Clearing…":<><Check className="h-4 w-4"/>Complete</>}</button>}</div></article>}

function QuestModal({quest,onClose,onSaved}:{quest:Quest|null;onClose:()=>void;onSaved:()=>void}){const{toast}=useToast();const isEdit=!!quest;const[title,setTitle]=useState(quest?.title??"");const[description,setDescription]=useState(quest?.description??"");const[category,setCategory]=useState<QuestCategory>(quest?.category??"study");const[difficulty,setDifficulty]=useState<QuestDifficulty>(quest?.difficulty??"easy");const[attribute,setAttribute]=useState<QuestAttribute>(quest?.attribute??"intellect");const[xp,setXp]=useState(quest?.xp_reward??30);const[gold,setGold]=useState(quest?.gold_reward??15);const[due,setDue]=useState(quest?.due_date??"");const[saving,setSaving]=useState(false);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!title.trim())return toast("Add a quest title","error");setSaving(true);const payload={title:title.trim(),description:description.trim(),category,difficulty,attribute,due_date:due||null};const result=isEdit?await supabase.from("quests").update(payload).eq("id",quest!.id):await supabase.from("quests").insert({...payload,xp_reward:Math.max(1,Math.min(1000,xp)),gold_reward:Math.max(0,Math.min(1000,gold))});if(result.error)toast(result.error.message,"error");else{toast(isEdit?"Quest updated":"Quest created","success");onSaved()}setSaving(false)};
 return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm" onMouseDown={onClose}><div className="panel max-h-[92vh] w-full max-w-2xl overflow-y-auto p-6 sm:p-7" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center justify-between"><div><div className="eyebrow text-sky-300">{isEdit?'Edit quest':'New quest'}</div><h2 className="mt-1 text-2xl font-black text-white">{isEdit?'Refine the mission.':'Add your next win.'}</h2></div><button onClick={onClose} className="rounded-xl p-2 text-slate-500 hover:bg-white/[0.05] hover:text-white"><X/></button></div><form onSubmit={submit} className="mt-6 space-y-5"><div><label className="eyebrow">Title</label><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Finish the first 3 chapters" className="field mt-2"/></div><div><label className="eyebrow">Description</label><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} placeholder="What does done look like?" className="field mt-2 resize-none"/></div><Pick label="Category" value={category} options={CATEGORIES.map(x=>[x.value,x.label])} onChange={setCategory}/><div className="grid gap-5 sm:grid-cols-2"><Pick label="Difficulty" value={difficulty} options={DIFFICULTIES.map(x=>[x.value,x.label])} onChange={setDifficulty}/><Pick label="Attribute" value={attribute} options={ATTRIBUTES.map(x=>[x.value,x.label])} onChange={setAttribute}/></div><div className="grid gap-5 sm:grid-cols-3"><div><label className="eyebrow">XP reward</label><input disabled={isEdit} type="number" min="1" max="1000" value={xp} onChange={e=>setXp(Number(e.target.value))} className="field mt-2 disabled:opacity-40"/></div><div><label className="eyebrow">Gold reward</label><input disabled={isEdit} type="number" min="0" max="1000" value={gold} onChange={e=>setGold(Number(e.target.value))} className="field mt-2 disabled:opacity-40"/></div><div><label className="eyebrow">Due date</label><input type="date" value={due} onChange={e=>setDue(e.target.value)} className="field mt-2 [color-scheme:dark]"/></div></div>{isEdit&&<div className="rounded-2xl border border-white/[0.06] bg-white/[0.025] p-3 text-xs text-slate-600">XP and gold are locked after creation to keep the economy fair.</div>}<div className="flex gap-3 pt-2"><button type="button" onClick={onClose} className="btn-secondary flex-1">Cancel</button><button disabled={saving} type="submit" className="btn-primary flex-1">{saving?<Clock3 className="h-4 w-4 animate-pulse"/>:<Plus className="h-4 w-4"/>}{isEdit?'Save changes':'Create quest'}</button></div></form></div></div>}
function Pick<T extends string>({label,value,options,onChange}:{label:string;value:T;options:[T,string][];onChange:(v:T)=>void}){return <div><label className="eyebrow">{label}</label><div className="mt-2 grid grid-cols-2 gap-2">{options.map(([v,l])=><button key={v} type="button" onClick={()=>onChange(v)} className={`rounded-xl border px-3 py-2.5 text-left text-xs font-bold transition ${value===v?'border-sky-400/30 bg-sky-400/10 text-sky-200':'border-white/[0.06] bg-white/[0.025] text-slate-500 hover:text-slate-200'}`}>{l}</button>)}</div></div>}
