import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/context/AuthContext";
import { supabase, type Item } from "@/lib/supabase";
import { useToast } from "@/components/Toast";
import { BadgeCheck, Castle, Check, Coins, Crown, Gem, Loader2, ShoppingBag, Sparkles, Sword, WandSparkles } from "lucide-react";
const ICONS={Sparkles,Sword,WandSparkles,Crown,Castle,BadgeCheck,Gem}; const TYPES:Record<Item["item_type"],string>={avatar:"Avatar",frame:"Frame",theme:"Theme",badge:"Badge"};
export function Shop(){const{profile,refreshProfile}=useAuth();const{toast}=useToast();const[items,setItems]=useState<Item[]>([]);const[owned,setOwned]=useState<Set<string>>(new Set());const[loading,setLoading]=useState(true);const[buying,setBuying]=useState<string|null>(null);const[type,setType]=useState<"all"|Item["item_type"]>("all");
 useEffect(()=>{(async()=>{setLoading(true);const[{data:a,error:e1},{data:b,error:e2}]=await Promise.all([supabase.from("items").select("*").order("price"),supabase.from("inventory").select("item_id")]);if(e1)toast(e1.message,"error");if(e2)toast(e2.message,"error");setItems((a??[]) as Item[]);setOwned(new Set((b??[]).map(x=>x.item_id)));setLoading(false)})()},[]);const filtered=useMemo(()=>type==="all"?items:items.filter(x=>x.item_type===type),[items,type]);const buy=async(item:Item)=>{setBuying(item.id);const{error}=await supabase.rpc("purchase_item",{item_uuid:item.id});if(error)toast(error.message,"error");else{setOwned(v=>new Set(v).add(item.id));await refreshProfile();toast(`${item.name} added to inventory`,"success")}setBuying(null)};
 return <div className="space-y-6 animate-enter"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="eyebrow text-amber-300">Guild shop</div><h1 className="mt-1 text-3xl font-black text-white sm:text-4xl">Customize your run.</h1><p className="mt-2 text-sm text-slate-500">Cosmetics only — spend gold without touching your progression.</p></div><div className="inline-flex items-center gap-2 self-start rounded-2xl border border-amber-400/10 bg-amber-400/5 px-4 py-3 font-black text-amber-200 sm:self-auto"><Coins className="h-5 w-5"/>{profile?.gold.toLocaleString()??0} gold</div></div><div className="panel flex flex-wrap gap-2 p-3">{(["all","avatar","frame","theme","badge"] as const).map(x=><button key={x} onClick={()=>setType(x)} className={`rounded-xl px-4 py-2 text-sm font-semibold capitalize ${type===x?'bg-white/[0.08] text-white':'text-slate-500 hover:text-white'}`}>{x}</button>)}</div>{loading?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3].map(i=><div key={i} className="panel h-60 animate-pulse"/>)}</div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(item=>{const Icon=ICONS[item.icon as keyof typeof ICONS]??Gem;const isOwned=owned.has(item.id);return <article key={item.id} className="panel group overflow-hidden p-5 transition hover:-translate-y-1 hover:border-amber-300/15"><div className="flex items-start justify-between"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br from-amber-400/15 to-violet-400/10 text-amber-200 group-hover:scale-105 transition"><Icon className="h-7 w-7"/></div><span className="rounded-full bg-white/[0.04] px-2.5 py-1 text-[10px] font-bold uppercase tracking-widest text-slate-600">{TYPES[item.item_type]}</span></div><h2 className="mt-6 text-lg font-black text-white">{item.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-slate-500">{item.description}</p><div className="mt-6 flex items-center justify-between gap-3"><div className="flex items-center gap-1.5 text-sm font-black text-amber-200"><Coins className="h-4 w-4"/>{item.price}</div><button disabled={isOwned||buying===item.id||((profile?.gold??0)<item.price)} onClick={()=>buy(item)} className={`rounded-xl px-4 py-2.5 text-sm font-bold transition ${isOwned?'bg-emerald-400/10 text-emerald-300':(profile?.gold??0)<item.price?'bg-white/[0.04] text-slate-600':'bg-amber-300 text-slate-950 hover:bg-amber-200'} disabled:opacity-60`}>{buying===item.id?<Loader2 className="h-4 w-4 animate-spin"/>:isOwned?<><Check className="mr-1 inline h-4 w-4"/>Owned</>:((profile?.gold??0)<item.price?'Need more gold':'Buy')}</button></div></article>})}</div>}</div>}
